name: HTML Proofer

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        env:
          PAT_TOKEN: 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
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build the site
        run: bundle exec jekyll build
      - name: Check for broken links
        run: bundle exec htmlproofer ./_site