name: HTML Proofer

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3
      - name: Install dependencies
        env:
          PAT_TOKEN: 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
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build the site
        run: bundle exec jekyll build
      - name: Check for broken links
        run: bundle exec htmlproofer ./_site